(function(){
  'use strict';
  const STORAGE_KEY='noviramCorporateAgentSession',LEGACY_KEY='noviramSalesAgentV1',MAX_MESSAGE_LENGTH=2000,MAX_HISTORY=14;
  const config=window.NOVIRAM_AGENT_CONFIG||{},apiBaseUrl=String(config.apiBaseUrl||'').replace(/\/$/,'');
  const pageContext=document.body.dataset.agentPageContext==='lead_engine_product_page'?'lead_engine_product_page':'corporate_home';
  let language=document.documentElement.lang==='en'?'en':'hu',busy=false,lastFailedMessage=null,activeController=null,requestEpoch=0,healthMode=null;
  let lastFailedActionId=null;
  const views=[];let floatingRoot=null,embeddedVisible=false;
  const I={
    hu:{title:'Noviram AI',subtitle:'Üzleti asszisztens',open:'Noviram AI',close:'Bezárás',reset:'Újrakezdés',welcome:'Üdv! Röviden írja le, mit szeretne megépíteni vagy javítani a vállalkozásában. A már megadott információkra nem kérdezek rá újra.',ready:'Készen állok',thinking:'Átgondolom…',offline:'Nincs internetkapcsolat',unavailable:'Az asszisztens jelenleg nem érhető el',failed:'Most nem sikerült választ kapnom. Próbálja újra, vagy írjon az info@noviram.com címre.',retry:'Újrapróbálás',empty:'Írjon be egy üzenetet.',tooLong:'Az üzenet legfeljebb 2000 karakter lehet.',placeholder:'Írja le, mit szeretne megoldani…',inputLabel:'Üzenet a Noviram AI-nak',send:'Üzenet küldése',mock:'TESZTÜZEM',summary:'Üzleti összefoglaló',summaryEmpty:'A beszélgetésben megismert üzleti adatok itt jelennek meg.',handoff:'Nézze át az összefoglalót, adja meg az elérhetőségét, majd küldje el a megkeresést. E-mailt csak ezzel a külön lépéssel küldünk.',email:'E-mail indítása',copy:'Összefoglaló másolása',copied:'Másolva.',resetConfirm:'Biztosan törli a közös Noviram AI-beszélgetést?',privacy:'Ne adjon meg bizalmas vagy különleges személyes adatot.',privacyLink:'Adatkezelés',contact:'Beszéljünk róla',ai:'NOVIRAM AI',language:'Nyelv: magyar',subject:'Projekt egyeztetése a Novirammal'},
    en:{title:'Noviram AI',subtitle:'Business assistant',open:'Noviram AI',close:'Close',reset:'Reset',welcome:"Hi! Briefly describe what you'd like to build or improve in your business. I won't ask again for details you already provided.",ready:'Ready',thinking:'Thinking…',offline:'You are offline',unavailable:'The assistant is currently unavailable',failed:"I couldn't get a response. Retry, or email info@noviram.com.",retry:'Retry',empty:'Please enter a message.',tooLong:'The message can be up to 2,000 characters.',placeholder:'Describe what you would like to improve…',inputLabel:'Message Noviram AI',send:'Send message',mock:'DEVELOPMENT MOCK',summary:'Business summary',summaryEmpty:'Business details from the conversation will appear here.',handoff:'Review the summary, add your contact details, then explicitly submit the enquiry. No email is sent automatically.',email:'Start email',copy:'Copy summary',copied:'Copied.',resetConfirm:'Delete the shared Noviram AI conversation?',privacy:'Do not provide confidential or sensitive personal information.',privacyLink:'Privacy',contact:'Contact Noviram',ai:'NOVIRAM AI',language:'Language: English',subject:'Noviram project discussion'}
  };
  const F={
    hu:{service_interest:'Lehetséges szolgáltatási irány',industry:'Iparág',company_name:'Cég',company_size_signal:'Cégméret',website:'Weboldal',location:'Helyszín',project_goal:'Cél',current_problem:'Fő probléma',current_solution:'Jelenlegi megoldás',lead_source:'Honnan érkeznek az érdeklődők',monthly_lead_volume:'Havi érdeklődőszám',desired_capabilities:'Egyeztetendő funkciók',project_stage:'Az elképzelés állapota',timeline:'Időzítés',budget_signal:'Tervezett keret',decision_role:'Döntési szerep',urgency:'Sürgősség',contact_name:'Kapcsolattartó',email:'E-mail',phone:'Telefon'},
    en:{service_interest:'Potential service fit',industry:'Industry',company_name:'Company',company_size_signal:'Company size',website:'Website',location:'Location',project_goal:'Goal',current_problem:'Core problem',current_solution:'Current solution',lead_source:'Lead source',monthly_lead_volume:'Monthly volume',desired_capabilities:'Capabilities to confirm',project_stage:'Idea or product stage',timeline:'Timeline',budget_signal:'Budget signal',decision_role:'Decision role',urgency:'Urgency',contact_name:'Contact',email:'Email',phone:'Phone'}
  };
  const SERVICE_DISPLAY={hu:{ai_automation:'AI és automatizáció',lead_engine:'Lead Engine',website:'Weboldal-tervezés és -fejlesztés',app:'Alkalmazásfejlesztés',growth_marketing:'Növekedés és digitális marketing',managed_services:'Üzemeltetés és támogatás',integrations:'Rendszerintegrációk',custom_unclear:'Egyedi / pontosítandó igény'},en:{ai_automation:'AI & Automation',lead_engine:'Lead Engine',website:'Website Design & Development',app:'App Development',growth_marketing:'Growth & Digital Marketing',managed_services:'Managed Services',integrations:'System integrations',custom_unclear:'Custom / needs clarification'}};
  const summaryFields=Object.keys(F.hu),txt=()=>I[language];
  const newId=()=>((crypto.randomUUID&&crypto.randomUUID())||('session_'+Date.now()+'_'+Math.random())).replace(/[-.]/g,'_');
  const blank=()=>({sessionId:newId(),language,state:{language,service_interest:[],desired_capabilities:[],conversation_stage:'discovery'},history:[],smartActions:[],handoff:false});
  function restore(){try{const value=sessionStorage.getItem(STORAGE_KEY)||sessionStorage.getItem(LEGACY_KEY),parsed=JSON.parse(value);if(parsed&&typeof parsed.sessionId==='string'&&Array.isArray(parsed.history)){sessionStorage.removeItem(LEGACY_KEY);if(parsed.language&&parsed.language!==language)return blank();parsed.language=language;return parsed;}}catch(_){}return blank();}
  let session=restore();
  function persist(){session.language=language;session.history=session.history.slice(-MAX_HISTORY);try{sessionStorage.setItem(STORAGE_KEY,JSON.stringify(session));}catch(_){}}
  function floatingMarkup(){return '<button class="noviram-ai-launcher" type="button" aria-expanded="false"><span class="noviram-ai-launcher-mark">N</span><span data-label="open"></span><span class="noviram-ai-unread" hidden>1</span></button><div class="noviram-ai-panel" role="dialog" aria-modal="true" aria-labelledby="noviramAiTitle" hidden><div class="noviram-ai-panel-head"><div class="agent-identity"><span class="agent-avatar">N</span><span class="agent-identity-text"><strong id="noviramAiTitle" data-label="title"></strong><small data-label="subtitle"></small></span></div><div class="agent-head-actions"><span class="agent-mode-badge" data-slot="mode"></span><button class="agent-reset" data-slot="reset" type="button"></button><button class="noviram-ai-close" data-slot="close" type="button" aria-label="Close">×</button></div></div><div class="agent-status-line" data-slot="status" data-state="ready"><span class="agent-status-dot"></span><span data-slot="statusText"></span></div><div class="agent-messages" data-slot="messages" role="log" aria-live="polite"></div><div class="agent-smart-actions" data-slot="actions"></div><div class="agent-error" data-slot="error" role="alert"><span data-slot="errorText"></span><button class="agent-retry" data-slot="retry" type="button"></button></div><form class="agent-composer" data-slot="form"><label class="agent-sr-only" data-label="inputLabel"></label><div class="agent-input-wrap"><textarea class="agent-input" data-slot="input" rows="1" maxlength="2000"></textarea><button class="agent-send" data-slot="send" type="submit"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg></button></div><div class="agent-input-meta"><span data-label="privacy"></span><span class="agent-char-count" data-slot="charCount">0 / 2000</span></div></form><details class="noviram-ai-summary"><summary data-label="summary"></summary><p class="agent-brief-empty" data-slot="summaryEmpty"></p><dl class="agent-summary-list" data-slot="summaryList"></dl><div class="agent-handoff" data-slot="handoff"><p class="agent-handoff-note" data-label="handoff"></p><div class="agent-handoff-actions"><a class="btn btn-primary" data-slot="email"></a><button class="btn btn-ghost" data-slot="copy" type="button"></button></div><div class="agent-copy-feedback" data-slot="copyFeedback"></div></div></details></div>';}
  function syncFloatingLauncher(){if(!floatingRoot)return;const launcher=floatingRoot.querySelector('.noviram-ai-launcher');const suppress=pageContext==='corporate_home'&&Boolean(document.getElementById('sales-agent'))&&embeddedVisible;floatingRoot.classList.toggle('is-embedded-visible',suppress);launcher.setAttribute('aria-hidden',String(suppress));launcher.tabIndex=suppress?-1:0;}
  function makeFloating(){const shell=document.createElement('div');shell.className='noviram-ai-shell';shell.dataset.agentView='floating';shell.innerHTML=floatingMarkup();document.body.appendChild(shell);const launcher=shell.querySelector('.noviram-ai-launcher'),panel=shell.querySelector('.noviram-ai-panel');let returnFocus=null;function open(){returnFocus=document.activeElement;panel.hidden=false;launcher.setAttribute('aria-expanded','true');document.body.classList.add('noviram-ai-open');shell.querySelector('[data-slot="input"]').focus();shell.querySelector('.noviram-ai-unread').hidden=true;}function close(){panel.hidden=true;launcher.setAttribute('aria-expanded','false');document.body.classList.remove('noviram-ai-open');const embeddedInput=document.querySelector('#sales-agent #agentInput');if(embeddedVisible&&embeddedInput)embeddedInput.focus();else (returnFocus&&returnFocus.focus?returnFocus:launcher).focus();syncFloatingLauncher();}launcher.addEventListener('click',()=>panel.hidden?open():close());shell.querySelector('[data-slot="close"]').addEventListener('click',close);panel.addEventListener('keydown',(e)=>{if(e.key==='Escape'){e.preventDefault();close();}else if(e.key==='Tab'){const items=[...panel.querySelectorAll('button,a,input,textarea,summary')].filter((x)=>!x.disabled&&x.offsetParent!==null);if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});return shell;}
  function createView(root,embedded){const q=(slot,id)=>root.querySelector('[data-slot="'+slot+'"]')||root.querySelector('#'+id);const v={root,embedded,form:q('form','agentForm'),input:q('input','agentInput'),send:q('send','agentSend'),messages:q('messages','agentMessages'),actions:q('actions','agentSmartActions'),status:q('status','agentStatus'),statusText:q('statusText','agentStatusText'),reset:q('reset','agentReset'),error:q('error','agentError'),errorText:q('errorText','agentErrorText'),retry:q('retry','agentRetry'),charCount:q('charCount','agentCharCount'),mode:q('mode','agentModeBadge'),summary:q('summaryList','agentSummaryList'),summaryEmpty:q('summaryEmpty','agentSummaryEmpty'),handoff:q('handoff','agentHandoff'),email:q('email','agentEmailHandoff'),copy:q('copy','agentCopySummary'),copyFeedback:q('copyFeedback','agentCopyFeedback')};v.form.addEventListener('submit',(e)=>{e.preventDefault();send(v.input.value);});v.input.addEventListener('keydown',(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();v.form.requestSubmit();}});v.input.addEventListener('input',()=>{resize(v);counters();clearErrors();});v.actions.addEventListener('click',(e)=>{const b=e.target.closest('[data-message]');if(!b||busy)return;const id=b.dataset.actionId;if(id==='contact_form_open'){window.dispatchEvent(new CustomEvent('noviram:contact'));return;}send(b.dataset.message,id);if(id==='contact_or_discussion_ready')window.dispatchEvent(new CustomEvent('noviram:contact'));});v.reset.addEventListener('click',()=>reset(true));v.retry.addEventListener('click',()=>lastFailedMessage&&send(lastFailedMessage,lastFailedActionId));v.copy.addEventListener('click',()=>copySummary(v));v.email.addEventListener('click',(e)=>{e.preventDefault();window.dispatchEvent(new CustomEvent('noviram:contact'));});const direct=document.createElement('button');direct.type='button';direct.className='agent-contact-direct';direct.dataset.label='contact';direct.dataset.noviramContact='';v.form.after(direct);const privacyLink=document.createElement('a');privacyLink.className='agent-privacy-link';privacyLink.dataset.noviramLegal='privacy';privacyLink.dataset.label='privacyLink';if(!v.form.querySelector('[data-noviram-legal="privacy"]'))v.form.querySelector('.agent-input-meta').appendChild(privacyLink);createConversationScroller(v);views.push(v);}
  function localize(){document.querySelectorAll('[data-label]').forEach((el)=>{if(txt()[el.dataset.label])el.textContent=txt()[el.dataset.label];});views.forEach((v)=>{v.input.placeholder=txt().placeholder;v.input.setAttribute('aria-label',txt().inputLabel);v.send.setAttribute('aria-label',txt().send);v.reset.textContent=txt().reset;v.retry.textContent=txt().retry;const close=v.root.querySelector('[data-slot="close"]');if(close)close.setAttribute('aria-label',txt().close);});window.NoviramLanguage?.refreshLinks(language);}
  function resize(v){v.input.style.height='auto';v.input.style.height=Math.min(v.input.scrollHeight,132)+'px';}
  function counters(){views.forEach((v)=>{v.charCount.textContent=v.input.value.length+' / '+MAX_MESSAGE_LENGTH;v.charCount.classList.toggle('visible',v.input.value.length>=1600);});}
  function msg(role,content,pending){const row=document.createElement('div');row.className='agent-message-row '+role;const bubble=document.createElement('div');bubble.className='agent-message';if(role==='assistant'){const label=document.createElement('span');label.className='agent-message-label';label.textContent=txt().ai;bubble.appendChild(label);}if(pending){const dots=document.createElement('span');dots.className='agent-thinking';dots.setAttribute('aria-label',txt().thinking);dots.innerHTML='<span></span><span></span><span></span>';bubble.appendChild(dots);}else bubble.appendChild(document.createTextNode(content));row.appendChild(bubble);return row;}
  function createConversationScroller(v){
    const scroller=document.createElement('div');scroller.className='agent-conversation';
    scroller.tabIndex=0;v.messages.before(scroller);scroller.append(v.messages,v.actions,v.error);
    const details=v.root.querySelector('.noviram-ai-summary');if(details)scroller.append(details);
    v.scroller=scroller;v.followLatest=true;
    const manualScroll=()=>{cancelAnimationFrame(v.scrollFrame);v.followLatest=false;};
    scroller.addEventListener('wheel',manualScroll,{passive:true});
    scroller.addEventListener('touchstart',manualScroll,{passive:true});
    scroller.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','PageUp','PageDown','Home','End'].includes(e.key))manualScroll();});
    scroller.addEventListener('scroll',()=>{v.followLatest=scroller.scrollHeight-scroller.clientHeight-scroller.scrollTop<32;},{passive:true});
  }
  function renderMessages(){views.forEach((v)=>{
    const follow=v.followLatest,top=v.scroller.scrollTop;
    v.messages.textContent='';v.messages.appendChild(msg('assistant',txt().welcome));
    session.history.forEach((m)=>v.messages.appendChild(msg(m.role,m.content)));
    if(busy)v.messages.appendChild(msg('assistant','',true));v.messages.setAttribute('aria-busy',String(busy));
    // Actions and summary render synchronously next. Scroll only after their
    // final layout, and preserve a reader's position when they moved upward.
    cancelAnimationFrame(v.scrollFrame);
    v.scrollFrame=requestAnimationFrame(()=>{v.scroller.scrollTop=follow?v.scroller.scrollHeight:top;v.followLatest=follow;});
  });}
  function renderActions(){views.forEach((v)=>{v.actions.textContent='';(session.smartActions||[]).slice(0,6).forEach((item)=>{if(!item||!item.message)return;const b=document.createElement('button');b.type='button';b.className='agent-smart-action';b.dataset.message=item.message.slice(0,240);b.dataset.actionId=item.id;b.textContent=item.label.slice(0,80);b.disabled=busy;v.actions.appendChild(b);});});}
  const display=(field,value)=>{if(field==='service_interest')return (Array.isArray(value)?value:[value]).map((item)=>SERVICE_DISPLAY[language][item]||SERVICE_DISPLAY[language].custom_unclear).join(', ');return Array.isArray(value)?value.join(', '):String(value);};
  function summaryText(){const lines=[language==='hu'?'Noviram üzleti összefoglaló':'Noviram business summary','',txt().language];summaryFields.forEach((key)=>{const value=session.state&&session.state[key];if(value!==null&&value!==undefined&&value!==''&&(!Array.isArray(value)||value.length))lines.push(F[language][key]+': '+display(key,value));});if(lines.length===3)return '';lines.push('',language==='hu'?'AI által készített üzleti összefoglaló — elküldés előtt ellenőrizendő.':'AI-prepared business summary — review before sending.');return lines.join('\n');}
  function renderSummary(){views.forEach((v)=>{v.summary.textContent='';let count=0;summaryFields.forEach((key)=>{const value=session.state&&session.state[key];if(value===null||value===undefined||value===''||(Array.isArray(value)&&!value.length))return;const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');row.className='agent-summary-item';dt.textContent=F[language][key];dd.textContent=display(key,value);row.append(dt,dd);v.summary.appendChild(row);count++;});v.summaryEmpty.hidden=count>0;v.summaryEmpty.textContent=txt().summaryEmpty;v.handoff.classList.toggle('visible',Boolean(session.handoff));v.email.textContent=txt().contact;v.copy.textContent=txt().copy;v.email.href='#business-enquiry';});}
  function setStatus(state,label){views.forEach((v)=>{v.status.dataset.state=state;v.statusText.textContent=label;});}
  function renderBusy(){views.forEach((v)=>{v.input.disabled=busy;v.send.disabled=busy;});setStatus(busy?'busy':(navigator.onLine?'ready':'error'),busy?txt().thinking:(navigator.onLine?txt().ready:txt().offline));renderMessages();renderActions();}
  function showError(message,retryable){views.forEach((v)=>{v.errorText.textContent=message;v.retry.hidden=!retryable;v.error.classList.add('visible');});setStatus('error',navigator.onLine?txt().unavailable:txt().offline);}
  function clearErrors(){views.forEach((v)=>v.error.classList.remove('visible'));}
  function render(){localize();renderBusy();renderSummary();counters();views.forEach(resize);views.forEach((v)=>{v.mode.classList.toggle('visible',healthMode==='mock');if(healthMode==='mock')v.mode.textContent=txt().mock;});}
  async function send(raw,actionId=null){const message=String(raw||'').trim();if(busy)return;if(!message){showError(txt().empty,false);return;}if(message.length>MAX_MESSAGE_LENGTH){showError(txt().tooLong,false);return;}if(!/(?:\b(?:don't|do not|not ready|not now)\b|\bnem\b|\bne\b)/i.test(message)&&/(?:besz[eé]lni szeretn[eé]k valakivel|emberrel szeretn[eé]k besz[eé]lni|talk to (?:someone|a person|a human)|speak (?:to|with) (?:someone|a person|a human))/i.test(message)){session.handoff=true;persist();renderSummary();window.dispatchEvent(new CustomEvent('noviram:contact'));}if(!navigator.onLine){lastFailedMessage=message;lastFailedActionId=actionId;showError(txt().failed,true);return;}clearErrors();lastFailedMessage=null;lastFailedActionId=null;views.forEach((v)=>{v.input.value='';resize(v);});session.history.push({role:'user',content:message});session.smartActions=[];persist();busy=true;const epoch=++requestEpoch;activeController=new AbortController();renderBusy();try{const response=await fetch(apiBaseUrl+'/api/agent/message',{method:'POST',headers:{'Content-Type':'application/json'},signal:activeController.signal,body:JSON.stringify({sessionId:session.sessionId,language,message,...(actionId?{actionId}:{}),state:session.state||{},history:session.history.slice(0,-1).slice(-MAX_HISTORY),pageContext})});const data=await response.json().catch(()=>null);if(epoch!==requestEpoch)return;if(!response.ok||!data||typeof data.reply!=='string'||!data.state)throw new Error('request_failed');session.history.push({role:'assistant',content:data.reply});session.state=data.state;session.smartActions=Array.isArray(data.smartActions)?data.smartActions:[];session.handoff=Boolean(data.handoff&&data.handoff.recommended);healthMode=data.mode;persist();busy=false;render();const floating=views.find((v)=>!v.embedded);if(floating&&floating.root.querySelector('.noviram-ai-panel').hidden)floating.root.querySelector('.noviram-ai-unread').hidden=false;}catch(error){if(epoch!==requestEpoch||error.name==='AbortError')return;session.history.pop();lastFailedMessage=message;lastFailedActionId=actionId;busy=false;views.forEach((v)=>v.input.value=message);persist();render();showError(txt().failed,true);}finally{if(epoch===requestEpoch)activeController=null;}}
  function reset(confirmFirst){if(confirmFirst&&!confirm(txt().resetConfirm))return;requestEpoch++;if(activeController)activeController.abort();busy=false;session=blank();window.dispatchEvent(new CustomEvent('noviram:corporatereset'));lastFailedMessage=null;lastFailedActionId=null;try{sessionStorage.removeItem(STORAGE_KEY);}catch(_){}persist();clearErrors();views.forEach((v)=>v.input.value='');render();setStatus(navigator.onLine?'ready':'error',navigator.onLine?txt().ready:txt().offline);}
  async function copySummary(v){try{await navigator.clipboard.writeText(summaryText());v.copyFeedback.textContent=txt().copied;}catch(_){v.copyFeedback.textContent=summaryText();}setTimeout(()=>v.copyFeedback.textContent='',3000);}
  async function health(){if(!navigator.onLine){setStatus('error',navigator.onLine?txt().unavailable:txt().offline);return;}try{const response=await fetch(apiBaseUrl+'/health'),data=await response.json();if(!response.ok||data.status!=='ok')throw new Error();healthMode=data.mode;render();setStatus('ready',txt().ready);}catch(_){setStatus('error',txt().unavailable);}}
  window.NoviramCorporateContact=Object.freeze({summary:summaryText,snapshot:()=>Object.fromEntries(summaryFields.filter((key)=>session.state&&session.state[key]!==undefined).map((key)=>[key,session.state[key]]))});
  const embedded=document.getElementById('sales-agent');if(embedded)createView(embedded,true);floatingRoot=makeFloating();createView(floatingRoot,false);if(embedded&&pageContext==='corporate_home'&&'IntersectionObserver'in window){const observer=new IntersectionObserver((entries)=>{const entry=entries[0];embeddedVisible=Boolean(entry&&entry.isIntersecting&&entry.intersectionRatio>=.35);syncFloatingLauncher();},{threshold:[0,.35,.6]});observer.observe(embedded);}render();health();
  // Keep the closed launcher clear of legal links without enlarging the footer.
  const footer=document.querySelector('footer');
  if(footer&&'IntersectionObserver'in window){
    const footerObserver=new IntersectionObserver(([entry])=>{
      floatingRoot.classList.toggle('is-footer-visible',entry.isIntersecting);
      floatingRoot.style.setProperty('--noviram-footer-offset',Math.ceil(entry.boundingClientRect.height+12)+'px');
    });
    footerObserver.observe(footer);
  }
  window.addEventListener('offline',()=>setStatus('error',txt().offline));window.addEventListener('online',health);window.addEventListener('noviram:languagechange',(e)=>{const next=e.detail&&e.detail.language==='en'?'en':'hu';if(next===language)return;language=next;reset(false);health();});
})();
